use_frameworks!

platform :ios, '9.0'

target 'Deeplinkable_Example' do
  pod 'Deeplinkable', :path => '../'
  
  target 'ModuleA' do
    pod 'Deeplinkable', :path => '../'
  end
  
  target 'ModuleB' do
    pod 'Deeplinkable', :path => '../'
  end
  
  target 'ModuleC' do
    pod 'Deeplinkable', :path => '../'
  end

  target 'Deeplinkable_Tests' do
    inherit! :search_paths

    
  end
end
